### ISSUE TITLE
Implement the Sum and Product trait

### ISSUE THREAD

**Issue by VictorGavrish** [olson-sean-k/decorum#13]
https://doc.rust-lang.org/std/iter/trait.Sum.html
https://doc.rust-lang.org/std/iter/trait.Product.html

These two.

Right now, instead of `iterator_of_r32.sum()` I have to write `iterator_of_r32.fold(R32::default(), |a, b| a + b)`.

**Comment by olson-sean-k** [comment]
Thanks for opening an issue; this is definitely an important omission! This should be fixed by b7976aa. I'll leave this issue open until those changes are released.

**Comment by olson-sean-k** [comment]
Released in `0.1.3`.
