### ISSUE TITLE
Ability to define const values

### ISSUE THREAD

**Issue by alxarch** [olson-sean-k/decorum#17]
Is there a way to define a `const FOO :R64 = 0.2;`?

**Comment by olson-sean-k** [comment]
I don't believe this will be possible until `const` functions support the type bounds used by `ConstrainedFloat` (currently only a bound on `Sized` can be used). Without a `const` function to initialize a `ConstrainedFloat`, there is no way to use `R64` or other proxy types in constant expressions. I believe there's more information in [this tracking issue](https://github.com/rust-lang/rust/issues/57563).
